### ISSUE TITLE
Unable to take more than one backup of a PersistentVolume

### ISSUE THREAD

**Issue by rosskukulinski** [StackPointCloud/ark-plugin-digitalocean#1]
Attempting to take additional backups of a PersistentVolume fail.

It appears that DO snapshots must have a unique name, but the this ark-plugin creates snapshots with a non-unique name:  https://github.com/StackPointCloud/ark-plugin-digitalocean/blob/master/ark-blockstore-digitalocean/main.go#L98

Ark logs from taking a second backup:
```
time="2018-08-21T16:10:53Z" level=info msg="Starting backup" backup=heptio-ark/nginx-example logSource="pkg/controller/backup_controller.go:339"
time="2018-08-21T16:10:57Z" level=info msg="Backup completed" backup=heptio-ark/nginx-example logSource="pkg/controller/backup_controller.go:401"
time="2018-08-21T16:12:30Z" level=info msg="Starting backup" backup=heptio-ark/nginx-example-with-logs logSource="pkg/controller/backup_controller.go:339"
time="2018-08-21T16:12:31Z" level=error msg="Storage.CreateSnapshot returned error: POST https://api.digitalocean.com/v2/volumes/c10061cd-a55c-11e8-bc72-0242ac114503/snapshots: 409 (request \"f9114d56-0932-4255-9146-b0ac57f874e0\") already exists" logSource="/go/src/github.com/heptio/ark-plugin-example/ark-blockstore-digitalocean/main.go:131" pluginName=ark-blockstore-digitalocean
time="2018-08-21T16:12:34Z" level=info msg="Backup completed" backup=heptio-ark/nginx-example-with-logs logSource="pkg/controller/backup_controller.go:401"
time="2018-08-21T16:12:35Z" level=error msg="backup failed" error="error creating snapshot: rpc error: code = Unavailable desc = transport is closing" key=heptio-ark/nginx-example-with-logs logSource="pkg/controller/backup_controller.go:280"
```

Ark users frequently take multiple backups of the same resources (e.g. via `ark schedule create`), so the DO Plugin should support creating multiple snapshots of the same persistent volume.

**Comment by skriss** [comment]
For reference, our in-tree Azure block store generates unique snapshot names:

https://github.com/heptio/ark/blob/master/pkg/cloudprovider/azure/block_store.go#L194

**Comment by edevenport** [comment]
Thank you both, the snapshot name is now unique and I pushed a `v0.1.0` image.

@rosskukulinski - Do you want to test again before we close this issue?

**Comment by rosskukulinski** [comment]
@edevenport I will test this morning

**Comment by rosskukulinski** [comment]
eh, maybe once DO stops having an API outage.

**Comment by rosskukulinski** [comment]
@edevenport I tested the v0.1.0 image and this issue is resolved. Thanks for your speedy response!
