### ISSUE TITLE
Velero 1.0.0 deployment breaks if plugin is added

### ISSUE THREAD

**Issue by archnode** [StackPointCloud/ark-plugin-digitalocean#13]
Velero 1.0.0 fails when this plugin is added, possibly because of a problem with the mount location of the cloud-credentials file.

On checking the configuration with ```velero server``` (same error in the logs):
> An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = NoCredentialProviders: no valid providers in chain. Deprecated.
> For verbose messaging see aws.Config.CredentialsChainVerboseErrors

Removing the plugin fixes the problem.

Otherwise: Thanks for your work on this module! Worked flawlessly up until now ;)

**Comment by jamonation** [comment]
The plugin is updated to work with velero 1.2.0 now.

See the [README.md](https://github.com/StackPointCloud/ark-plugin-digitalocean/blob/master/README.md) for details on how to use it

**Comment by archnode** [comment]
Thank you - this fixed the issue!
