### ISSUE TITLE
Plugin docker image includes other plugins

### ISSUE THREAD

**Issue by rosskukulinski** [StackPointCloud/ark-plugin-digitalocean#2]
The published docker image for this Plugin includes all of the example Ark plugins as well as the DO plugin.

```
$ docker run --entrypoint=/bin/sh --rm -ti  quay.io/stackpoint/ark-blockstore-digitalocean:latest
~ $ ls
bin      dev      etc      home     lib      media    mnt      plugins  proc     root     run      sbin     srv      sys      tmp      usr      var
~ $ cd plugins/
/plugins $ ls
ark-backupitemaction-log-and-annotate   ark-blockstore-digitalocean             ark-objectstore-file                    ark-restoreitemaction-log-and-annotate
```
The Docker image should only have the one digitalocean plugin.

**Comment by edevenport** [comment]
@rosskukulinski Looks like I forgot to run `make clean` before pushing the image up. This has been done now and I pushed a new image.

**Comment by rosskukulinski** [comment]
Great! Thanks @edevenport.  Just tested the fresh image. 

Have y'all thought about a versioning/tagging scheme for images?

**Comment by edevenport** [comment]
I was looking for some feedback and further testing before I tagged an official release. So thank you for that! Let me address your other issue and then we can look at tagging the image.

I'm just not sure what an appropriate plugin version would be given Ark is still pre-1.0.0 itself. Thoughts?

**Comment by nrb** [comment]
@edevenport I'd probably opt for 0.1.0, myself.

As a note, we've updated the plugin handling mechanisms in `master` and they'll be changing. We'll be getting the example repo cleaned up and cutting branches to map to Ark releases when that happens.

**Comment by skriss** [comment]
yeah, i'd say anything less than 1.0 would be fine - probably when Ark cuts a v1.0, you'll want to do the same, and then they can vary independently from there

**Comment by edevenport** [comment]
Thanks, Everyone. I have tagged and pushed a `v0.1.0` image.
